name: Continuous Integration (lint, unit test)

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./webapp/
    steps:
      - uses: actions/checkout@v2
      - name: Linting frontend with Node.js ${{ matrix.node-version }}
        run: |
              yarn install
              yarn lint

  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./webapp/
    steps:
      - uses: actions/checkout@v2
      - name: Testing frontend with Node.js ${{ matrix.node-version }}
        run: |
              yarn install
              yarn test

  lint-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - uses: actions/checkout@v2
      - name: Linting backend 
        run: |
              yarn install
              yarn lint

  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
       working-directory: ./backend/
    
    steps:
      - uses: actions/checkout@v2
      - name: Testing backend 
        run: |
              yarn install
              yarn test
