# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    defaults:
      run:
        working-directory: ./webapp/

    steps:
      - uses: actions/checkout@v2
      - name: Linting frontend with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing ⏬
        run: yarn install
      - name: Run lint 🧪
        run: yarn lint

  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    defaults:
      run:
        working-directory: ./webapp/

    steps:
      - uses: actions/checkout@v2
      - name: Testing frontend with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing ⏬
        run: yarn install
      - name: Run tests 🧪
        run: yarn test:unit

  lint-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - uses: actions/checkout@v2
      - name: Linting backend 
      - name: Installing ⏬
        run: yarn install
      - name: Run lint 🧪
        run: yarn lint

  # test-backend:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
    
  #   defaults:
  #     run:
  #       working-directory: ./backend/

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Testing backend 
  #     - name: Installing ⏬
  #       run: yarn install
  #     - name: Run tests 🧪
  #       run: yarn test


