# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Linting with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing ⏬
        run: yarn install
      - name: Run lint 🧪
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Testing with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing ⏬
        run: yarn install
      - name: Run tests 🧪
        run: yarn test:unit

  build-backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    defaults:
      run:
        working-directory: ./backend/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing ⏬
        run: yarn install
      - name: Run lint 🧪
        run: yarn lint
      - name: Run tests 🧪
        run: yarn test
