name: Continuous Integration (lint, unit test)

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main, excercise-2 ]
  pull_request:
    branches: [ main, excercise-2 ]

defaults:
  run:
    working-directory: ./exercises/webapp/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: check lint
        run: yarn lint
      - name: check tests
        run: yarn test:unit
      - name: The job has succeeded
        if: ${{ success() }}
  
